server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/newaustriancodingschool/i4-configuration
          
management:
  endpoints:
    web:
      exposure:
        include: "*"